language: node_js
node_js:
  - "8.11.4"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run lint
  - yarn run build:prod

deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
